name: pritam_dutta_resume
services:
  pritam-resume:
    cpu_shares: 50
    command: []
    container_name: Pritam-Resume
    deploy:
      resources:
        limits:
          memory: 8192M
    entrypoint:
      - /bin/bash
      - -c
      - " apt update && apt install -y build-essential gcc libc6-dev libc-dev &&
        cd /usr/src/ && apt install gcc -y && go mod tidy && go build &&
        ./resume"
    environment:
      - BUILD=true
      - DB_DATABASE=resume
      - DB_HOST=192.168.1.105
      - DB_PASSWORD=nasDI72]zI6*t*9d
      - DB_PORT=3306
      - DB_USER=resume
      - SERVER_PORT=1080
      - SESSION_STORE_TYPE=db
    hostname: Pritam-Resume
    image: golang:1.24.3
    labels:
      icon: https://icon.casaos.io/main/all/go-app.png
    ports:
      - target: 1080
        published: "1080"
        protocol: tcp
    privileged: true
    restart: unless-stopped
    volumes:
      - type: bind
        source: /home/pritamresume
        target: /usr/src
    working_dir: /usr/src
    devices: []
    cap_add: []
    network_mode: bridge
x-casaos:
  author: self
  category: self
  hostname: ""
  icon: https://icon.casaos.io/main/all/go-app.png
  index: /
  is_uncontrolled: false
  port_map: "1080"
  scheme: http
  store_app_id: compassionate_rally
  title:
    custom: Pritam Resume
    en_us: go-app
